### ISSUE TITLE
Use "outputStyle: 'compressed'," instead of "minify-css"

### ISSUE THREAD

**Issue by smoench** [DavidBadura/symfony-standard-edition#1]
``` js
.pipe(sass({
   includePaths: ['node_modules/bootstrap-sass/assets/stylesheets/'],
   errLogToConsole: true,
   outputStyle: 'compressed'
}))
```

It isn't documented but node-sass supports it

**Comment by DavidBadura** [comment]
i know this option but if you have css files, you need compress it too. so i need minify-css for not sass files :wink:

**Comment by DavidBadura** [comment]
someday i will replace sass with postcss. so i close this.
